### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by gonzaloaguilarjimenez** [aravindk2604/publishAirsimImgs#2]
Good afternoon; 

I am trying to use your files to connect AirSim and ROS in order to control and send images, but I am getting an error when doing catkin_make. 

What I get after the catkin_make command is:

![image](https://user-images.githubusercontent.com/35638894/50405319-0a02b200-07b3-11e9-8275-8f8638fbd3c6.png)

Could you please help me to solve it? 

Thanks a lot.

Best regards.

**Comment by aravindk2604** [comment]
Export the path of the g++ AirSim directory as an environment variable AIRSIM_PATH before building the project (i.e before doing catkin_make).

`export AIRSIM_PATH=~/your_work_directory/AirSim/`

**Comment by gonzaloaguilarjimenez** [comment]
Good morning again, 

Firstly, thanks for your quick answer. 

I am doing it as you mentioned on your message (you can see it below), but it does not work.

![image](https://user-images.githubusercontent.com/35638894/50422362-6664e080-084a-11e9-952e-0c2fd054e87e.png)

It seems that still the program does not fint the file:

/home/gonzalo/airsim_catkin_ws/src/publishAirsimImgs/src/myTeleop.cpp:3:48: fatal error: vehicles/car/api/CarRpcLibClient.hpp: No existe el archivo o el directorio

But the file exists because I know where it is and also I exported the path ( maybe I did it wrong but I don't think so, since the path is very simple).

Also, I've seen that the file of the g++ AirSim, the vehicles/car/api/CarRpcLibClient.hpp is not really a .hpp but a .cpp, maybe is this the reason?

Any other idea? 

Thanks again.

Best regards.

**Comment by Yueting-Li** [comment]
Good morning,
  I met the problem the same with you. And I didn't work it out. So could you please help me solve it now?
  Thanks a lot.
  Best regards.
